name: Deploy

on: push

jobs:
 first_job:
  runs-on: ubuntu-latest

  steps:
   - name: Print Variable
     run: echo "${{ secrets.USER }}"

   - name: getnvm
     uses: dcodeIO/setup-node-nvm@master
     with:
       node-version: lts/*


   - name: checkout
     uses: actions/checkout@v4

   - name: prepare
     run: |
          cd pages
          npm install -g @angular/cli
          npm install
          npm run build
          pwd

   - name: Deploy
     if: success()
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./pages/dist/pages/browser
       enable_jekyll: true
     

    
       
